SUPABASE_URL = https://ehybkmzdtynnuywujzxj.supabase.co
SUPABASE_KEY = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVoeWJrbXpkdHlubnV5d3VqenhqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjkwMTc4OTIsImV4cCI6MjA4NDU5Mzg5Mn0.Mj2oDUee4aBs0zJAWVfoAi9Jt-I4WUZHYxQ37e_GEiI
